#!/usr/bin/env python

# NB: only required for development mode due to an issue with Werkzeug's
#     reloader (cf. https://github.com/mitsuhiko/flask/issues/1246) - otherwise
#     use `python -m taskard.server`

from taskard.server import main


main()
